version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
executors:
  build-executor:
    docker:
      - image: circleci/node:lts
    working_directory: /tmp
jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: web-ui
          paths:
            - dist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    executor: build-executor
    steps:
      - attach_workspace:
          at: /tmp/web-ui
      - aws-s3/sync:
          from: /tmp/web-ui/dist
          to: 's3://website-showcase'
          arguments: |
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master