version: 2.1
executors:
  build-executor:
    docker:
      - image: circleci/node:lts
jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run: sudo apt-get install python-pip && sudo pip install awscli
      - run: awscli sync /tmp/web-ui/dist s3://website-showcase --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master